### PR TITLE
Camera detection sensor

### PR DESCRIPTION
**Pull request by stvnmbr1**
first time trying a hassio addon sensor, how did I do? 🥇  or 👎

### CODE REVIEW

**Comment by stvnmbr1** [comment]
i used my template logic to config the extra attributes and an extra detection sensor.
not sure if we need the original sensor as it gets 'events' from the camera section in API

in my case only last 10mins are parsed, i can do a PR for that but its just deleting the if section is_important  and set timestamp to 60 *10

edit: 
do i have to PR this to the repo of reddragon?

**Comment by stvnmbr1** [comment]
not that good looks like it..

ERROR (MainThread) [homeassistant.components.sensor] Error while setting up badnest platform for sensor
 File "/config/custom_components/badnest/sensor.py", line 60, in async_setup_platform

what did i do wrong?

**Comment by slinkymanbyday** [comment]
> do i have to PR this to the repo of reddragon?

If you want it in that repo, sure, I have no control of what goes in there. I started this fork becuase it seems camera fixes were not being merged in.

>what did i do wrong?

There seems to be a few error. mainly, you can only reference values in python dictionaries that exist, for example, when you do self.device.device_data[self.device_id]["events"][-1]["types"][2], if there are not 3 types (it's zero indexed), then this will raise an exception.

I would avoid splitting out the types and zone list into separate fields and keep them as lists since there's not a consistent number. 

Something to consider too is this detector will remain on doorbell, even long after doorbell is pressed if no other events come after it. do you think there should be a timeout on returning the last event? maybe say 30 seconds?

I have made a bunch of changes on my end to make this work and add more configuration (make the is_important and how many minutes configurable), will upload them over the weekend. but curious to what your opinion is on the detector event timeout.

**Comment by stvnmbr1** [comment]
We'll work on this in your branch then, those who need this setup will get to this fork through the issue on reddragons repo anyways. Why wait when we can dev further ;) 
No biggie on the late response, it works for now and there is no hurry ;) 

hmm, that's a tricky one.. types doesn't always have 3 objects defined. maybe we could set dummy zonesids to 0 before parsing the api? but..
I would prefer not to split them up though, if we could use some kind of wildcard in the template value for the attribute array in hassio, like : if_state_attr(...) contains zoneid or == *zoneid* or anything else for automation?
Reason i split them up was lazy coding for automation :D

edit: i misunderstood this part`
In my case the zonenumbers are consistent, i don't know if you have nest aware and activity zones setup in the nest app? I use the zonenumber to only notify through alexa when an event is detect in a set zone and works like a charm. still some hackles when the are multiple types detected but we'll get there.`


Right now the badnest door events sensor actually goes to unavailable when there are no events in the last 10mins. This should be None preferably 

the extra detection sensor shows the last event without unavailable or none, with time ago.
state is also set to the first object in types (i do think there is some prioritizing in there and again lazy coding for automation).

For me personally, i like to see the last detected event and when in a glance so i don't want that timeout. automation only kicks in when the state is changed to doorbell, so i see no harm in leaving it in that state.
 Maybe this could be an option in the config to have it with none or null values or to not update the sens with none or nulls?

**Comment by stvnmbr1** [comment]
could add binary sensors that switches on for x time when eg. motion or doorbell press is detected?

**Comment by slinkymanbyday** [comment]
Merging this in after doing some fixes. 
I have put a timeout on the dector, so that old events won't come up, however you can set this to the same or grater as camera_event_minutes, and then it shouldn't really change anything for you.

As for automation of testing if a value is in a list (for example, if zone_id in the list of zone_ids).
`"face" in state_attr("sensor.front_door_events", "events")[0]["types"]`

**Pull request merged**
